name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

env:
  ZIG_VERSION: 0.14.1

jobs:
  build-test:
    name: build & test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
          cache-key: ${{ matrix.os }}-${{ env.ZIG_VERSION }}

      # Zig fmt is failing on windows and is redundant to run all platforms. So we run only on linux.
      - name: Check formatting
        if: matrix.os == 'ubuntu-latest'
        run: zig fmt --check .

  spec-tests:
    name: spec tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
          cache-key: ubuntu-latest-${{ env.ZIG_VERSION }}

      - name: zig build
        run: zig build

      - name: Cache spec tests
        id: spec-tests
        uses: actions/cache@v4
        with:
          path: test/spec/spec_tests
          key: ${{ hashFiles('test/spec/version.txt') }}

      - name: Download spec tests
        run: |
          zig build download_spec_tests

      - name: Write spec tests
        run: |
          zig build write_spec_tests

      - name: Run spec tests
        run: |
          zig build run_spec_tests
